### ISSUE TITLE
8.5 Header Files Demo Lab Instructions

### ISSUE THREAD

**Issue by DonMacary** [CyberTrainingUSAF/05-C-Programming#13]
The instructions for 8.5 header files demo lab says at the end to run Unit Test Code2.c but it should say run string_theory.c! This is super confusing... 

Currently:
Purpose - Print a table of letters from the string with their count
Write a program that reads a string from user input and then calls print_the_count()
When satisfied, run "Unit Test Code 2.c"

Should be 
Purpose - Print a table of letters from the string with their count
Write a program that reads a string from user input and then calls print_the_count()
When satisfied, run "string_theory.c"

If the users run Unit Test Code 2.c then they get a error on compiling it because reverse it has not been created even though it is defined.

**Comment by Tercilian** [comment]
This error has been corrected in the curriculum. Thank you for the input
